In [1]:
import numpy as np

np.set_printoptions(suppress=True)

In [2]:
from simulators import NestedModelFamily, ContextManager
from simulators.benchmarks import DDM

In [3]:
ddm_intrinsics = ["v", "a", "tau", "s_v", "s_tau", "decay"]

In [4]:
ddm_priors = {
    "v":     {"intercept": lambda: np.random.gamma(3.0, 0.8),
              "slope":     lambda: np.random.normal(0.0, 3.0)},
    "a":     {"intercept": lambda: np.random.gamma(10.0, 0.3),
              "slope":     lambda: np.random.normal(0.0, 1.0)},
    "tau":   {"intercept": lambda: np.random.gamma(3.0, 0.2),
              "slope":     lambda: 0.0},
    "s_v":   {"intercept": lambda: np.random.gamma(1.0, 0.2),
              "slope":     lambda: 0.0},
    "s_tau": {"intercept": lambda: np.random.uniform(0.0, 0.4),
              "slope":     lambda: 0.0},
    "decay": {"intercept": lambda: np.random.gamma(1.0, 0.4),
              "slope":     lambda: 0.0},
}

In [5]:
context_manager = ContextManager()

family = NestedModelFamily(
    name="DDM",
    model=DDM(),
    context_manager=context_manager,
    prior_fun=ddm_priors,
    intrinsic_params=ddm_intrinsics,
)

In [6]:
samples = family.batch_sample(
    batch_size=6,
    mask_randomizer_kwargs=dict(
        free_intrinsics={"v", "a", "tau", "decay"},
        fixed_intrinsics={"s_tau", "s_v"}
    ),
    min_num_obs=20,
    max_num_obs=500,
    keep_intercept=True,
    flatten_param_outputs=False,
    visualize=False
)

In [7]:
design_matrices = samples["design_matrices"]

In [8]:
param_matrices = samples["param_matrices"]

In [9]:
samples

{'model_names': ['DDM', 'DDM', 'DDM', 'DDM', 'DDM', 'DDM'],
 'design_configs': [{'1': ['v', 'a', 'tau', 's_v', 's_tau', 'decay'],
   'u_1': ['v', 'a', 'decay'],
   'u_2': ['v', 'tau', 'decay'],
   'u_3': ['v', 'a', 'decay'],
   'u_4': ['tau'],
   'u_5': ['v', 'a', 'decay'],
   'u_6': ['v', 'tau'],
   'u_7': ['v', 'a', 'tau', 'decay'],
   'u_8': [],
   'u_9': ['a', 'tau']},
  {'1': ['v', 'a', 'tau', 's_v', 's_tau', 'decay'],
   'u_1': ['a', 'tau'],
   'u_2': ['v', 'a', 'tau'],
   'u_3': [],
   'u_4': ['v', 'a'],
   'u_5': ['v']},
  {'1': ['v', 'a', 'tau', 's_v', 's_tau', 'decay'],
   'u_1': ['a', 'tau', 'decay'],
   'u_2': ['v', 'a', 'decay'],
   'u_3': ['v', 'a', 'decay']},
  {'1': ['v', 'a', 'tau', 's_v', 's_tau', 'decay'],
   'u_1': ['decay'],
   'u_2': ['tau', 'decay'],
   'u_3': [],
   'u_4': ['v', 'a'],
   'u_5': [],
   'u_6': ['a', 'tau', 'decay'],
   'u_7': ['a', 'decay']},
  {'1': ['v', 'a', 'tau', 's_v', 's_tau', 'decay'], 'u_1': ['a']},
  {'1': ['v', 'a', 'tau', 's_v', 's_tau

In [10]:
design_matrices.shape

(6, 378, 27)

In [11]:
param_matrices.shape

(6, 28, 6)

In [85]:
param_matrices[0, 0]

array([1.030258  , 4.38990592, 0.24728913, 0.12761956, 0.26552746,
       0.26187433])

In [86]:
param_matrices[0, 1]

array([0., 0., 0., 0., 0., 0.])

In [53]:
param_matrices

array([[[ 5.19771076,  2.63464549,  1.80027235,  0.40301722,
          0.0062883 ,  0.2769946 ],
        [ 0.        ,  1.60767869,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        , -0.72263189,  0.        ,  0.        ,
          0.        ,  0.        ],
        ...,
        [ 0.        ,  0.71654842,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  2.22860519,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.88885361,  0.        ,  0.        ,
          0.        ,  0.        ]],

       [[ 4.72044671,  1.15497954,  0.53100444,  0.04632048,
          0.24789278,  0.91542168],
        [ 0.        , -2.41257657,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        , -0.80709276,  0.        ,  0.        ,
          0.        ,  0.        ],
        ...,
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
  

In [60]:
import torch

In [59]:
samples['param_masks'].reshape((6, -1))

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.]], shape=(6, 186))

In [57]:
samples['regressor_masks'].shape

(6, 31)